language: python
python:
  - "3.8"

branches:
  only:
    - main

install:
  - python -m pip install --upgrade setuptools==70.0.0
  - python -m pip install -r requirements.txt
  - python -m pip install black flake8 coverage coveralls

before_script:
  - black --check .  
  - flake8           

script:
  - coverage run -m pytest
  - coverage report

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "sweapp1"        
  env: "swe1-app-env"             
  bucket_name: "elasticbeanstalk-us-east-1-095179586850"  
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  on:
    branch: main

after_success:
  - coveralls